//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikOcagi
{
    using System;
    using System.Collections.Generic;
    
    public partial class cikis
    {
        public int dosyaNo { get; set; }
        public System.DateTime sevkTarihi { get; set; }
        public Nullable<System.DateTime> cikisTarihi { get; set; }
        public string odemeSekli { get; set; }
        public string toplamTutar { get; set; }
    }
}
