//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikOcagi
{
    using System;
    using System.Collections.Generic;
    
    public partial class hasta
    {
        public int TC { get; set; }
        public int dosyaNo { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string dogumYeri { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public string babaAdi { get; set; }
        public string anneAdi { get; set; }
        public string cinsiyet { get; set; }
        public string kanGrubu { get; set; }
        public string telefonNo { get; set; }
        public string adres { get; set; }
        public string yakiniAdres { get; set; }
        public string kurumSicilNo { get; set; }
        public string kurumAdi { get; set; }
        public string yakinTelefonNo { get; set; }
        public string yakinKurumSicilNo { get; set; }
        public string yakinKurumAdi { get; set; }
        public string medeniHal { get; set; }
    }
}
