//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikOcagi
{
    using System;
    using System.Collections.Generic;
    
    public partial class sevk
    {
        public System.DateTime sevkTarihi { get; set; }
        public int dosyaNo { get; set; }
        public string poliklinik { get; set; }
        public string saat { get; set; }
        public string yapilanIslem { get; set; }
        public string doktorKod { get; set; }
        public string miktar { get; set; }
        public string birimFiyat { get; set; }
        public string sira { get; set; }
        public string toplamTutar { get; set; }
        public string taburcu { get; set; }
    }
}
